### ISSUE TITLE
StaticMan

### ISSUE THREAD

**Issue by SidVal** [GonzaloZiadi/windespair#1]
Hi. :+1:  
It's me again :D 

https://github.com/GonzaloZiadi/windespair/blob/master/staticman.yml#L77
_data/ comments? 

```
  # (*) REQUIRED
  #
  # Destination path (directory) for the data files. Accepts placeholders.
  path: "_data/comments/{options.slug}"
```

Try other path.

**Comment by GonzaloZiadi** [comment]
What should I change it to? I just copied the example. I just added a dummy .txt file so that the _data/comments directories show up on github.

**Comment by SidVal** [comment]
Did you add staticman bot to you account?

**Comment by GonzaloZiadi** [comment]
Yes.
<img width="757" alt="screen shot 2017-07-25 at 8 11 32 am" src="https://user-images.githubusercontent.com/7485384/28571449-ef86c540-7110-11e7-9c2c-3e7f9f2916b3.png">

Should I remove the permission and try again?

**Comment by SidVal** [comment]
Please delete some fields, and put the same fields that uses eduardo in example.
Let's see if it works with simple fields.

**Comment by GonzaloZiadi** [comment]
I switched to Eduardo's fields and staticman and it's working now...

I'll slowly add fields back on and see what the issue was.

Thank you for the help!

**Comment by SidVal** [comment]
Ok.

I bet there is some conflict with new fields.
Add one, test.
Add one more, test again.

:+1:

**Comment by GonzaloZiadi** [comment]
@SidVal 
Slowly added everything back on and it's now working as I wanted it to! Thanks for the help!
